# Generated by Django 5.0.6 on 2026-06-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('script_prompt', models.TextField(blank=True)),
                ('first_message', models.TextField(blank=True)),
                ('extraction_schema', models.JSONField(default=list)),
                ('voice_id', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(default='en', max_length=8)),
                ('concurrency', models.PositiveIntegerField(default=2)),
                ('retry_delay_minutes', models.PositiveIntegerField(default=60)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('retry_on', models.JSONField(default=list)),
                ('eleven_agent_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('context', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('retry_wait', 'Retry Wait'), ('completed', 'Completed'), ('failed', 'Failed'), ('exhausted', 'Exhausted')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_outcome', models.CharField(blank=True, max_length=32)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField()),
                ('conversation_id', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(blank=True, choices=[('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('voicemail', 'Voicemail'), ('declined', 'Declined'), ('wrong_number', 'Wrong Number')], max_length=32)),
                ('transcript', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='campaigns.campaigncontact')),
            ],
            options={
                'ordering': ['attempt_no'],
            },
        ),
    ]
