# Generated by Django 5.0.6 on 2026-06-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='eleven_agent_ids',
            field=models.JSONField(default=list),
        ),
    ]
