# Generated by Django 5.0.6 on 2026-06-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_eleven_agent_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callattempt',
            name='transcript',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='eleven_agent_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='extraction_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='retry_on',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campaigncontact',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
