# Generated by Django 5.0.6 on 2026-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_callattempt_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
