# Generated by Django 5.0.6 on 2026-06-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_send_sms_campaigncontact_sms_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dealership_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
